name: Accounts Trigger

on:
  workflow_call:
    inputs:
      json_file_path:
        required: true
        type: string
      json_file:
        required: true
        type: string
      gh_environment:
        required: true
        type: string

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Set up Python virtual environment
        run: python -m venv .env

      - name: Install dependencies
        run: |
          source .env/bin/activate
          pip install aws-cdk-lib

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Process JSON file
        run: |
          source .env/bin/activate
          echo "Processing JSON file: ${{ inputs.json_file_path }}/${{ inputs.json_file }}"
          echo "Environment: ${{ inputs.gh_environment }}"

      - name: Synthesize CDK app
        run: |
          source .env/bin/activate
          cdk synth --app "python AWSControlTowerAccountFactory/account_creation_template/aws_control_tower_account_factory_stack/app.py" -c filepath=${{ inputs.json_file_path }}/${{ inputs.json_file }}

      - name: Deploy CDK stack
        run: |
          source .env/bin/activate
          cdk deploy AWSControlTowerAccountFactoryStack-Demo-Account12 --app "python AWSControlTowerAccountFactory/account_creation_template/aws_control_tower_account_factory_stack/app.py" -c filepath=${{ inputs.json_file_path }}/${{ inputs.json_file }} --require-approval never