name: Accounts Trigger

on:
  workflow_call:
    inputs:
      json_file_path:
        required: true
        type: string
      json_file:
        required: true
        type: string
      gh_environment:
        required: true
        type: string

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Set up Python virtual environment
        run: python -m venv .env

      - name: Install dependencies
        run: |
          source .env/bin/activate
          pip install aws-cdk-lib

      - name: Process JSON file
        run: |
          source .env/bin/activate
          # Your script to process the JSON file using the inputs
          echo "Processing JSON file: ${{ inputs.json_file_path }}/${{ inputs.json_file }}"
          echo "Environment: ${{ inputs.gh_environment }}"

      - name: Deploy CDK stack
        run: |
          source .env/bin/activate
          cdk deploy AWSControlTowerAccountFactoryStack-Demo-Account12 --app "python /home/runner/work/CDK-Training/CDK-Training/.github/data/accounts/Demo_Account12_sso.json" -c filepath=${{ inputs.json_file_path }}/${{ inputs.json_file }} --require-approval never