name: 04 - AWS Account Creation and SSO Mapping CDK Deploy Trigger Workflow
on:
  workflow_dispatch:

env:
  ALPHA: true
  BETA: false
  RELEASE: false

permissions:
  contents: write
  id-token: write

jobs:
  SELECT_ENVIRONMENT:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment
        id: set-env
        run: |
          echo "ALPHA=${{ env.ALPHA }}" >> $GITHUB_ENV
          echo "BETA=${{ env.BETA }}" >> $GITHUB_ENV
          echo "RELEASE=${{ env.RELEASE }}" >> $GITHUB_ENV
    outputs:
      ALPHA: ${{ env.ALPHA }}
      BETA: ${{ env.BETA }}
      RELEASE: ${{ env.RELEASE }}

  PROCESS_JSON_FILES:
    needs: [SELECT_ENVIRONMENT]
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment related JSON Files
        id: set_deployment_files
        shell: bash
        run: | 
          # echo ALPHA_FILES='["accounts/Demo_Account5", "accounts/Demo_Account9", "accounts/Demo_Account10", "accounts/Demo_Account12"]' >> $GITHUB_OUTPUT
          echo 'ALPHA_FILES=["sso-groups/Demo_Account6_sso", "sso-groups/Demo_Account9_sso", "sso-groups/Demo_Account10_sso", "sso-groups/Demo_Account12_sso"]' >> $GITHUB_OUTPUT
          echo 'BETA_FILES=[]' >> $GITHUB_OUTPUT
          echo 'RELEASE_FILES=[]' >> $GITHUB_OUTPUT
    outputs: 
      alpha_deployment_files_output: ${{ steps.set_deployment_files.outputs.ALPHA_FILES }}
      beta_deployment_files_output: ${{ steps.set_deployment_files.outputs.BETA_FILES }}
      release_deployment_files_output: ${{ steps.set_deployment_files.outputs.RELEASE_FILES }}

  ALPHA:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: ${{ needs.SELECT_ENVIRONMENT.outputs.ALPHA == 'true' }}
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.alpha_deployment_files_output) }}
    uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
    with:
      json_file_path: .github/workflows/data
      json_file: ${{ matrix.json_file }}
      gh_environment: ALPHA

  BETA:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: ${{ needs.SELECT_ENVIRONMENT.outputs.BETA == 'true' }}
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.beta_deployment_files_output) }}
    uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
    with:
      json_file_path: .github/workflows/data
      json_file: ${{ matrix.json_file }}
      gh_environment: BETA

  RELEASE:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: ${{ needs.SELECT_ENVIRONMENT.outputs.RELEASE == 'true' }}
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.release_deployment_files_output) }}
    uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
    with:
      json_file_path: .github/workflows/data
      json_file: ${{ matrix.json_file }}
      gh_environment: RELEASE

  VALIDATE_TEMPLATE:
    runs-on: ubuntu-latest
    steps:
      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template --template-body file://path/to/your/template.yaml
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  DEPLOY_STACK:
    needs: [VALIDATE_TEMPLATE]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy CloudFormation Stack
        run: |
          echo "Deploying CloudFormation stack..."
          aws cloudformation deploy --stack-name AwsSSOGroupMappingStack --template-file path/to/your/template.yaml --capabilities CAPABILITY_NAMED_IAM
          echo "Waiting for stack update or creation to complete..."
          aws cloudformation wait stack-update-complete --stack-name AwsSSOGroupMappingStack || aws cloudformation wait stack-create-complete --stack-name AwsSSOGroupMappingStack
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}