name: 04 - AWS Account Creation and SSO Mapping CDK Deploy Trigger Workflow
on:
  workflow_dispatch:

env:
  ALPHA: True
  BETA: False
  RELEASE: False
  
permissions:
  contents: write
  id-token: write

jobs:
  SELECT_ENVIRONMENT:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment
        id: set-env
        run: |
          echo "ALPHA=${{ env.ALPHA }}" >> $GITHUB_ENV
          echo "BETA=${{ env.BETA }}" >> $GITHUB_ENV
          echo "RELEASE=${{ env.RELEASE }}" >> $GITHUB_ENV

    outputs:
      ALPHA: ${{ env.ALPHA }}
      BETA: ${{ env.BETA }}
      RELEASE: ${{ env.RELEASE }}

  PROCESS_JSON_FILES:
    needs: [SELECT_ENVIRONMENT]
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment related JSON Files
        id: set_deployment_files
        shell: bash
        run: | 
          echo "ALPHA_FILES='[\"accounts/Demo_Account21\",\"accounts/Demo_Account22\"]'" >> $GITHUB_ENV
          echo "BETA_FILES='[]'" >> $GITHUB_ENV
          echo "RELEASE_FILES='[]'" >> $GITHUB_ENV

    outputs: 
      alpha_deployment_files_output: ${{ env.ALPHA_FILES }}
      beta_deployment_files_output: ${{ env.BETA_FILES }}
      release_deployment_files_output: ${{ env.RELEASE_FILES }}

  SET_STACK_NAME_ALPHA:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: needs.SELECT_ENVIRONMENT.outputs.ALPHA == 'True'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.alpha_deployment_files_output) }}
    steps:
      - name: Set Stack Name
        id: set-stack-name
        run: |
          stack_name="AWSControlTowerAccountFactoryStack-${{ matrix.json_file }}" | sed 's/_/-/g'
          echo "stack_name=${stack_name}" >> $GITHUB_ENV
          echo "stack_name=${stack_name}" >> $GITHUB_OUTPUT

    outputs:
      stack_name: ${{ steps.set-stack-name.outputs.stack_name }}
      json_file: ${{ matrix.json_file }}

  DEPLOY_ALPHA:
    needs: [SET_STACK_NAME_ALPHA]
    if: needs.SELECT_ENVIRONMENT.outputs.ALPHA == 'True'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.alpha_deployment_files_output) }}
    steps:
      - name: CDK Deploy
        uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
        with:
          json_file_path: .github/workflows/data
          json_file: ${{ matrix.json_file }}
          gh_environment: ALPHA
          stack_name: ${{ needs.SET_STACK_NAME_ALPHA.outputs.stack_name }}

  SET_STACK_NAME_BETA:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: needs.SELECT_ENVIRONMENT.outputs.BETA == 'True'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.beta_deployment_files_output) }}
    steps:
      - name: Set Stack Name
        id: set-stack-name
        run: |
          stack_name="AWSControlTowerAccountFactoryStack-${{ matrix.json_file }}" | sed 's/_/-/g'
          echo "stack_name=${stack_name}" >> $GITHUB_ENV
          echo "stack_name=${stack_name}" >> $GITHUB_OUTPUT

    outputs:
      stack_name: ${{ steps.set-stack-name.outputs.stack_name }}
      json_file: ${{ matrix.json_file }}

  DEPLOY_BETA:
    needs: [SET_STACK_NAME_BETA]
    if: needs.SELECT_ENVIRONMENT.outputs.BETA == 'True'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.beta_deployment_files_output) }}
    steps:
      - name: CDK Deploy
        uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
        with:
          json_file_path: .github/workflows/data
          json_file: ${{ matrix.json_file }}
          gh_environment: BETA
          stack_name: ${{ needs.SET_STACK_NAME_BETA.outputs.stack_name }}

  SET_STACK_NAME_RELEASE:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: needs.SELECT_ENVIRONMENT.outputs.RELEASE == 'True'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.release_deployment_files_output) }}
    steps:
      - name: Set Stack Name
        id: set-stack-name
        run: |
          stack_name="AWSControlTowerAccountFactoryStack-${{ matrix.json_file }}" | sed 's/_/-/g'
          echo "stack_name=${stack_name}" >> $GITHUB_ENV
          echo "stack_name=${stack_name}" >> $GITHUB_OUTPUT

    outputs:
      stack_name: ${{ steps.set-stack-name.outputs.stack_name }}
      json_file: ${{ matrix.json_file }}

  DEPLOY_RELEASE:
    needs: [SET_STACK_NAME_RELEASE]
    if: needs.SELECT_ENVIRONMENT.outputs.RELEASE == 'True'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.release_deployment_files_output) }}
    steps:
      - name: CDK Deploy
        uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
        with:
          json_file_path: .github/workflows/data
          json_file: ${{ matrix.json_file }}
          gh_environment: RELEASE
          stack_name: ${{ needs.SET_STACK_NAME_RELEASE.outputs.stack_name }}