name: 04 - AWS Account Creation and SSO Mapping CDK Deploy Trigger Workflow

on:
  workflow_dispatch:

env:
  ALPHA: True
  BETA: False
  RELEASE: False

permissions:
  contents: write
  id-token: write

jobs:
  SELECT_ENVIRONMENT:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment
        id: set-env
        run: |
          echo ALPHA=$ALPHA >> $GITHUB_OUTPUT
          echo BETA=$BETA >> $GITHUB_OUTPUT
          echo RELEASE=$RELEASE >> $GITHUB_OUTPUT

    outputs:
      ALPHA: ${{ steps.set-env.outputs.ALPHA }}
      BETA: ${{ steps.set-env.outputs.BETA }}
      RELEASE: ${{ steps.set-env.outputs.RELEASE }}

  PROCESS_JSON_FILES:
    needs: [SELECT_ENVIRONMENT]
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment related JSON Files
        id: set_deployment_files
        shell: bash
        run: | 
          echo ALPHA_FILES='["accounts/Demo_Account22", "accounts/Demo_Account21"]' >> $GITHUB_OUTPUT
          echo BETA_FILES='[]' >> $GITHUB_OUTPUT
          echo RELEASE_FILES='[]' >> $GITHUB_OUTPUT

    outputs: 
      alpha_deployment_files_output: ${{ steps.set_deployment_files.outputs.ALPHA_FILES }}
      beta_deployment_files_output: ${{ steps.set_deployment_files.outputs.BETA_FILES }}
      release_deployment_files_output: ${{ steps.set_deployment_files.outputs.RELEASE_FILES }}

  ALPHA:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: needs.SELECT_ENVIRONMENT.outputs.ALPHA == 'True'
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.alpha_deployment_files_output) }}
    uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
    with:
      json_file_path: .github/workflows/data
      json_file: ${{ matrix.json_file }}
      gh_environment: ALPHA
      stack_name: AWSControlTowerAccountFactoryStack-ALPHA

  BETA:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: needs.SELECT_ENVIRONMENT.outputs.BETA == 'True'
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.beta_deployment_files_output) }}
    uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
    with:
      json_file_path: .github/workflows/data
      json_file: ${{ matrix.json_file }}
      gh_environment: BETA
      stack_name: AWSControlTowerAccountFactoryStack-BETA

  RELEASE:
    needs: [SELECT_ENVIRONMENT, PROCESS_JSON_FILES]
    if: needs.SELECT_ENVIRONMENT.outputs.RELEASE == 'True'
    strategy:
      fail-fast: true
      matrix:
        json_file: ${{ fromJSON(needs.PROCESS_JSON_FILES.outputs.release_deployment_files_output) }}
    uses: MeroneYilma/CDK-Training/.github/workflows/cdk_deploy.yaml@alpha
    with:
      json_file_path: .github/workflows/data
      json_file: ${{ matrix.json_file }}
      gh_environment: RELEASE
      stack_name: AWSControlTowerAccountFactoryStack-Demo-Account21, AWSControlTowerAccountFactoryStack-Demo-Account22