name: CDK Deploy Workflow
on:   
  workflow_call: 
    inputs:
      json_file_path:
        description: 'Specifies the JSON file path.'
        required: true
        type: string
      json_file:
        description: 'Specifies the JSON Data file.'
        required: true
        type: string
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: true
        type: string
        
jobs:    
  CDK_DEPLOY: 
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write # This is required for actions/checkout 

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Use AWS Configure Custom Action
        id: aws_configure
        uses: MeroneYilma/CDK-Training/.github/actions/global/aws_github_auth@alpha
        with: 
          json_data_file: "./${{ inputs.json_file_path }}/${{ inputs.json_file }}.json"

      - name: Use AWS CDK Working Directory Custom Action
        id: cdk_directory
        uses: MeroneYilma/CDK-Training/.github/actions/global/cdk_directory@alpha
        with: 
          json_data_file: "./${{ inputs.json_file_path }}/${{ inputs.json_file }}.json"

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install Requirements 
        run: 'pip install -r requirements.txt'
        working-directory: ${{ steps.cdk_directory.outputs.working_directory_output }}

      - name: Check if JSON file exists
        run: |
          if [ ! -f "./${{ inputs.json_file_path }}/${{ inputs.json_file }}.json" ]; then
            echo "File not found: ./${{ inputs.json_file_path }}/${{ inputs.json_file }}.json"
            exit 1
          fi
        working-directory: ${{ steps.cdk_directory.outputs.working_directory_output }}

      - name: CDK Deploy
        run: cdk deploy -c filepath=../../../../${{ inputs.json_file_path }}/${{ inputs.json_file }}.json --all 
        working-directory: ${{ steps.cdk_directory.outputs.working_directory_output }}