name: CDK Deploy Workflow
on:   
  workflow_call: 
    inputs:
      json_file_path:
        description: 'Specifies the JSON file path.'
        required: true
        type: string
      json_file:
        description: 'Specifies the JSON Data file.'
        required: true
        type: string
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: true
        type: string
        
jobs:    
  CDK_DEPLOY: 
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write # This is required for actions/checkout 

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: List repository contents
        # List the contents of the repository to verify the directory structure
        run: ls -al

      - name: List lib directory contents
        # List the contents of the lib directory to verify the directory structure
        run: ls -al lib

      - name: List Iac directory contents
        # List the contents of the Iac directory to verify the directory structure
        run: ls -al lib/Iac

      - name: Use AWS Configure Custom Action
        id: aws_configure
        uses: MeroneYilma/CDK-Training/.github/actions/global/aws_github_auth@alpha
        with: 
          json_data_file: "./${{ inputs.json_file_path }}/${{ inputs.json_file }}.json"

      - name: Use AWS CDK Working Directory Custom Action
        id: cdk_directory
        uses: MeroneYilma/CDK-Training/.github/actions/global/cdk_directory@alpha
        with: 
          json_data_file: "./${{ inputs.json_file_path }}/${{ inputs.json_file }}.json"

      - name: List directory contents
        # List the contents of the working directory to verify it exists
        run: ls -al ${{ steps.cdk_directory.outputs.working_directory_output }}

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install Requirements 
        # Install the requirements in the specified working directory
        run: pip install -r requirements.txt
        working-directory: ${{ steps.cdk_directory.outputs.working_directory_output }}

      - name: Print Filepath
        # Print the filepath to debug the path being accessed
        run: echo "Filepath: ../../../../${{ inputs.json_file_path }}/${{ inputs.json_file }}.json"
        working-directory: ${{ steps.cdk_directory.outputs.working_directory_output }}

      - name: CDK Deploy
        # Deploy using the CDK in the specified working directory
        run: cdk deploy -c filepath=../../../../${{ inputs.json_file_path }}/${{ inputs.json_file }}.json --all 
        working-directory: ${{ steps.cdk_directory.outputs.working_directory_output }}