name: Deploy CDK Stack SSO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install CDK
      run: npm install -g aws-cdk

    - name: Set up virtual environment
      run: python -m venv .env

    - name: Activate virtual environment
      shell: bash
      run: source .env/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install AWS CDK library
      run: pip install aws-cdk-lib

    - name: Deploy CDK Stack
      run: cdk deploy AwsssoGroupMappingStack-Account-SSODemoAccount12 -c filepath=Demo_Account12_sso.json --require-approval never
      working-directory: AWSControlTowerAccountFactory/account_creation_template/aws_sso_group_mapping_stack