name: Deploy CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv .env
        source .env/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Deploy CDK Stack
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        source .env/bin/activate
        cdk deploy  --app "python app.py" AWSControlTowerAccountFactoryStack-Demo-Account12 -c filepath=".github/data/accounts/Demo_Account12.json" --require-approval never --require-approval never