name: Deploy AWS CDK Stack for New SSO

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AWSControlTowerAccountFactory/account_creation_template/aws_sso_group_mapping_stack

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Set up Python virtual environment
        run: python -m venv .env

      - name: Install dependencies
        run: |
          source .env/bin/activate
          pip install -r requirements.txt
          pip install aws-cdk-lib

      - name: Debug - List files in root directory
        run: ls -al ../../../../

      - name: Debug - List files in CDK-Training directory
        run: ls -al ../../../../CDK-Training/CDK-Training/.github/data/sso-groups

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CDK stack
        run: |
          source .env/bin/activate
          cdk deploy AwsssoGroupMappingStack-Account-SSODemoAccount12 -c filepath=../../../../CDK-Training/CDK-Training/.github/data/sso-groups/Demo_Account12_sso.json --require-approval never