name: Deploy CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AWSControlTowerAccountFactory/account_creation_template/aws_sso_group_mapping_stack

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install CDK
      run: npm install -g aws-cdk

    - name: Initialize CDK app
      run: cdk init app --language python

    - name: Set up virtual environment
      run: python -m venv .env

    - name: Activate virtual environment
      run: . ./.env/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install AWS CDK library
      run: pip install aws-cdk-lib

    - name: Deploy CDK Stack
      run: cdk deploy AwsssoGroupMappingStack-Account-SSODemoAccount12 -c filepath=Demo_Account12_sso.json --require-approval never
      working-directory: AWSControlTowerAccountFactory/account_creation_template/aws_sso_group_mapping_stack