name: Deploy CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      shell: bash
      run: |
        python -m venv .env
        source .env/Scripts/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install AWS CDK locally
      working-directory: AWSControlTowerAccountFactory/account_creation_template/aws_control_tower_account_factory_stack
      shell: bash
      run: |
        source .env/Scripts/activate
        npm install aws-cdk

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy stack
      working-directory: AWSControlTowerAccountFactory/account_creation_template/aws_control_tower_account_factory_stack
      shell: bash
      run: |
        source .env/Scripts/activate
        npx cdk deploy AWSControlTowerAccountFactoryStack-Demo-Account12 -c filepath=Demo_Account12.json --app "python app.py" --require-approval never