name: Deploy CDK Stack SSO

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Set up Python virtual environment
        run: python -m venv .env

      - name: Verify virtual environment creation
        run: ls -la .env/bin

      - name: Install dependencies
        run: |
          . .env/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; fi
          pip install aws-cdk-lib

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CDK Stack
        run: |
          . .env/bin/activate
          cdk deploy AwsssoGroupMappingStack-Account-SSODemoAccount12 -c filepath=Demo_Account12_sso.json --require-approval never
        working-directory: AWSControlTowerAccountFactory/account_creation_template/aws_sso_group_mapping_stack