name: SSO Mapping Trigger

on:
  workflow_call:
    inputs:
      json_file_path:
        required: true
        type: string
      json_file:
        required: true
        type: string
      gh_environment:
        required: true
        type: string

permissions:
  id-token: write  # Allows the workflow to request an OIDC token
  contents: read

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Set up Python virtual environment
        run: python -m venv .env

      - name: Install dependencies
        run: |
          source .env/bin/activate
          pip install aws-cdk-lib

      - name: Configure AWS used to authenticate with GitHub
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::209479296537:role/GitHubAction-AssumeRoleWithAction
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Process JSON file
        run: |
          source .env/bin/activate
          echo "Processing JSON file: ${{ inputs.json_file_path }}/${{ inputs.json_file }}"
          echo "Environment: ${{ inputs.gh_environment }}"

      - name: Synthesize CDK app
        run: |
          source .env/bin/activate
          cdk synth --app "python AWSControlTowerAccountFactory/account_creation_template/aws_sso_group_mapping_stack/app.py" -c filepath=${{ inputs.json_file_path }}/${{ inputs.json_file }}

      - name: Deploy CDK stack
        run: |
          source .env/bin/activate
          cdk deploy AwsssoGroupMappingStack-Account-SSODemoAccount10 --app "python AWSControlTowerAccountFactory/account_creation_template/aws_sso_group_mapping_stack/app.py" -c filepath=${{ inputs.json_file_path }}/${{ inputs.json_file }} --require-approval never